#!/bin/sh
COMMAND="hhvm -v Hack.Lang.AutoTypecheck=0"
for template in `ls STU/Model/*.harm`
do
	NAME=`echo $template | sed -e 's/.harm//'`
	echo "Generating $NAME"
	$COMMAND vendor/bin/harmgen table $template > $NAME"Table.hh"
	$COMMAND vendor/bin/harmgen interface $template > $NAME"TableInterface.hh"
done
